// @flow

import type { SurveyMaterialFormat } from "../../material-survey-format.js.flow"

export default {
  pages: [
    {
      name: "Background Information",
      elements: [
        {
          type: "radiogroup",
          name: "refugee",
          title:
            "Have you been forced to leave your home due to climate change, conflict, or economic instability?",
          choices: ["Yes", "No"]
        },
        {
          type: "dropdown",
          name: "home",
          visibleIf: '{refugee} = "Yes"',
          title: "What is your home country?  Where are you from?",
          hasOther: true,
          choices: [
            "Afghanistan",
            "Albania",
            "Algeria",
            "Andorra",
            "Angola",
            "Antigua and Barbuda",
            "Argentina",
            "Armenia",
            "Australia",
            "Austria",
            "Azerbaijan",
            "Bahamas",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Belgium",
            "Belize",
            "Benin",
            "Bhutan",
            "Bolivia",
            "Bosnia and Herzegovina",
            "Botswana",
            "Brazil",
            "Brunei",
            "Bulgaria",
            "Burkina Faso",
            "Burundi",
            "Cabo Verde",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Central African Republic (CAR)",
            "Chad",
            "Chile",
            "China",
            "Colombia",
            "Comoros",
            "Democratic Republic of the Congo",
            "Republic of the Congo",
            "Costa Rica",
            "Cote d'Ivoire",
            "Croatia",
            "Cuba",
            "Cyprus",
            "Czech Republic",
            "Denmark",
            "Djibouti",
            "Dominica",
            "Dominican Republic",
            "Ecuador",
            "Egypt",
            "El Salvador",
            "Equatorial Guinea",
            "Eritrea",
            "Estonia",
            "Eswatini (formerly Swaziland)",
            "Ethiopia",
            "Fiji",
            "Finland",
            "France",
            "Gabon",
            "Gambia",
            "Georgia",
            "Germany",
            "Ghana",
            "Greece",
            "Grenada",
            "Guatemala",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Honduras",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Iran",
            "Iraq",
            "Ireland",
            "Israel",
            "Italy",
            "Jamaica",
            "Japan",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kiribati",
            "Kosovo",
            "Kuwait",
            "Kyrgyzstan",
            "Laos",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liberia",
            "Libya",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Macedonia (FYROM)",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Marshall Islands",
            "Mauritania",
            "Mauritius",
            "Mexico",
            "Micronesia",
            "Moldova",
            "Monaco",
            "Mongolia",
            "Montenegro",
            "Morocco",
            "Mozambique",
            "Myanmar (formerly Burma)",
            "Namibia",
            "Nauru",
            "Nepal",
            "Netherlands",
            "New Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "North Korea",
            "Norway",
            "Oman",
            "Pakistan",
            "Palau",
            "Palestine",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Poland",
            "Portugal",
            "Qatar",
            "Romania",
            "Russia",
            "Rwanda",
            "Saint Kitts and Nevis",
            "Saint Lucia",
            "Saint Vincent and the Grenadines",
            "Samoa",
            "San Marino",
            "Sao Tome and Principe",
            "Saudi Arabia",
            "Senegal",
            "Serbia",
            "Seychelles",
            "Sierra Leone",
            "Singapore",
            "Slovakia",
            "Slovenia",
            "Solomon Islands",
            "Somalia",
            "South Africa",
            "South Korea",
            "South Sudan",
            "Spain",
            "Sri Lanka",
            "Sudan",
            "Suriname",
            "Swaziland (renamed to Eswatini)",
            "Sweden",
            "Switzerland",
            "Syria",
            "Taiwan",
            "Tajikistan",
            "Tanzania",
            "Thailand",
            "Timor-Leste",
            "Togo",
            "Tonga",
            "Trinidad and Tobago",
            "Tunisia",
            "Turkey",
            "Turkmenistan",
            "Tuvalu",
            "Uganda",
            "Ukraine",
            "United Arab Emirates (UAE)",
            "United Kingdom (UK)",
            "United States of America (USA)",
            "Uruguay",
            "Uzbekistan",
            "Vanuatu",
            "Vatican City (Holy See)",
            "Venezuela",
            "Vietnam",
            "Yemen",
            "Zambia",
            "Zimbabwe"
          ]
        },
        {
          type: "dropdown",
          name: "current_location",
          title: "Where are you currently living?",
          hasOther: true,
          choices: [
            "Afghanistan",
            "Albania",
            "Algeria",
            "Andorra",
            "Angola",
            "Antigua and Barbuda",
            "Argentina",
            "Armenia",
            "Australia",
            "Austria",
            "Azerbaijan",
            "Bahamas",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Belgium",
            "Belize",
            "Benin",
            "Bhutan",
            "Bolivia",
            "Bosnia and Herzegovina",
            "Botswana",
            "Brazil",
            "Brunei",
            "Bulgaria",
            "Burkina Faso",
            "Burundi",
            "Cabo Verde",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Central African Republic (CAR)",
            "Chad",
            "Chile",
            "China",
            "Colombia",
            "Comoros",
            "Democratic Republic of the Congo",
            "Republic of the Congo",
            "Costa Rica",
            "Cote d'Ivoire",
            "Croatia",
            "Cuba",
            "Cyprus",
            "Czech Republic",
            "Denmark",
            "Djibouti",
            "Dominica",
            "Dominican Republic",
            "Ecuador",
            "Egypt",
            "El Salvador",
            "Equatorial Guinea",
            "Eritrea",
            "Estonia",
            "Eswatini (formerly Swaziland)",
            "Ethiopia",
            "Fiji",
            "Finland",
            "France",
            "Gabon",
            "Gambia",
            "Georgia",
            "Germany",
            "Ghana",
            "Greece",
            "Grenada",
            "Guatemala",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Honduras",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Iran",
            "Iraq",
            "Ireland",
            "Israel",
            "Italy",
            "Jamaica",
            "Japan",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kiribati",
            "Kosovo",
            "Kuwait",
            "Kyrgyzstan",
            "Laos",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liberia",
            "Libya",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Macedonia (FYROM)",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Marshall Islands",
            "Mauritania",
            "Mauritius",
            "Mexico",
            "Micronesia",
            "Moldova",
            "Monaco",
            "Mongolia",
            "Montenegro",
            "Morocco",
            "Mozambique",
            "Myanmar (formerly Burma)",
            "Namibia",
            "Nauru",
            "Nepal",
            "Netherlands",
            "New Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "North Korea",
            "Norway",
            "Oman",
            "Pakistan",
            "Palau",
            "Palestine",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Poland",
            "Portugal",
            "Qatar",
            "Romania",
            "Russia",
            "Rwanda",
            "Saint Kitts and Nevis",
            "Saint Lucia",
            "Saint Vincent and the Grenadines",
            "Samoa",
            "San Marino",
            "Sao Tome and Principe",
            "Saudi Arabia",
            "Senegal",
            "Serbia",
            "Seychelles",
            "Sierra Leone",
            "Singapore",
            "Slovakia",
            "Slovenia",
            "Solomon Islands",
            "Somalia",
            "South Africa",
            "South Korea",
            "South Sudan",
            "Spain",
            "Sri Lanka",
            "Sudan",
            "Suriname",
            "Swaziland (renamed to Eswatini)",
            "Sweden",
            "Switzerland",
            "Syria",
            "Taiwan",
            "Tajikistan",
            "Tanzania",
            "Thailand",
            "Timor-Leste",
            "Togo",
            "Tonga",
            "Trinidad and Tobago",
            "Tunisia",
            "Turkey",
            "Turkmenistan",
            "Tuvalu",
            "Uganda",
            "Ukraine",
            "United Arab Emirates (UAE)",
            "United Kingdom (UK)",
            "United States of America (USA)",
            "Uruguay",
            "Uzbekistan",
            "Vanuatu",
            "Vatican City (Holy See)",
            "Venezuela",
            "Vietnam",
            "Yemen",
            "Zambia",
            "Zimbabwe"
          ]
        },
        {
          type: "radiogroup",
          name: "gender",
          title: "What is your gender?",
          description:
            "We ask because some jobs are Market or Social Science Research Surveys where the client wants respondents to be a specific gender.",
          choices: ["Male", "Female", "Other"]
        },
        {
          type: "text",
          name: "household_members",
          title: "How many people are in your household?",
          description: "Count yourself plus anyone who you help support",
          validators: [
            {
              type: "numeric",
              text:
                "Be sure to count yourself.  Only include people living with you that you help support.",
              minValue: 1,
              maxValue: 20
            }
          ],
          inputType: "number"
        },
        {
          type: "checkbox",
          name: "channel",
          title: "How did you hear about WorkAround?",
          hasOther: true,
          choices: [
            "Facebook",
            "Twitter",
            "Google Search",
            "Friend/Family",
            "Paper Airplanes",
            "Rainbow Street",
            "MIT React",
            "Talent Beyond Boundaries",
            "Dubarah",
            "UNHCR"
          ]
        }
      ]
    },
    {
      name: "Education",
      elements: [
        {
          type: "radiogroup",
          name: "ed_level",
          title: "What is your highest level of education?",
          isRequired: true,
          validators: [
            {
              type: "numeric",
              minValue: 0,
              maxValue: 50
            }
          ],
          choices: [
            "no school",
            {
              value: "less than 8 years of primary school",
              text: "primary school"
            },
            "some high school",
            "high school diploma",
            "some college",
            "associate's degree",
            "bachelor's degree",
            "master's degree",
            "PhD"
          ]
        },
        {
          type: "dropdown",
          name: "field",
          visibleIf:
            '{ed_level} = "some college"or\n{ed_level} = "associate\'s degree"or\n{ed_level} = "bachelor\'s degree" or\n{ed_level} = "master\'s degree" or\n{ed_level} = "PhD"',
          title: "What is your primary field/area of study?",
          hasOther: true,
          choices: [
            "Agriculture",
            "Anthropology",
            "Architecture and design",
            "Astrology",
            "Biology",
            "Business",
            "Chemistry",
            "Computer science",
            "Economics",
            "Education",
            "Engineering",
            "Environmental studies",
            "Ethnic and cultural studies",
            "Family and consumer science",
            "Gender and sexuality studies",
            "Geography",
            "Geology",
            "History",
            "Journalism",
            "Law",
            "Library and museum science",
            "Linquistics and languages",
            "Literature",
            "Mathematics",
            "Medicine",
            "Military science",
            "Performing Arts",
            "Philosophy",
            "Physics",
            "Political Science",
            "Psychology",
            "Public Policy",
            "Recreation and sports",
            "Religion",
            "Social work",
            "Sociology",
            "Systems science",
            "Technology",
            "Tourism",
            "Transportation",
            "Visual Arts"
          ]
        },
        {
          type: "checkbox",
          name: "tests",
          title: "Did you take any of these tests?",
          description: "check all that apply",
          hasOther: true,
          choices: [
            "TOEFL iBT (Test of English as a Foreign Language Internet-Based Test)",
            "TOEFL paper based test",
            "IELTS Academic (International English Language Testing System)",
            "PTE Academic (Pearsons Test of English Academic)",
            {
              value:
                "C1 Advanced or C2 Proficiency (Cambridge English: Advanced or Proficiency)",
              text: "Cambridge English Test (A2, B1, B2, C1, C2)"
            },
            "SAT",
            "ACT"
          ]
        },
        {
          type: "multipletext",
          name: "TOEFL iBT",
          visibleIf:
            '{tests} contains "TOEFL iBT (Test of English as a Foreign Language Internet-Based Test)"',
          title: "Enter your TOEFL iBT scores",
          validators: [
            {
              type: "numeric",
              minValue: 0,
              maxValue: 30
            }
          ],
          items: [
            {
              name: "text1",
              title: "reading"
            },
            {
              name: "text2",
              title: "writing"
            },
            {
              name: "text3",
              title: "listening"
            },
            {
              name: "text4",
              title: "speaking"
            },
            {
              name: "text5",
              title: "total"
            }
          ]
        },
        {
          type: "multipletext",
          name: "TOEFL",
          visibleIf: '{tests} contains "TOEFL paper based test"',
          title: "Enter your TOEFL paper based scores",
          items: [
            {
              name: "text1",
              title: "reading"
            },
            {
              name: "text2",
              title: "writing"
            },
            {
              name: "text3",
              title: "listening"
            },
            {
              name: "text4",
              title: "speaking"
            },
            {
              name: "text5",
              title: "total"
            }
          ]
        },
        {
          type: "rating",
          name: "IELTS",
          visibleIf:
            '{tests} contains "IELTS Academic (International English Language Testing System)"',
          title: "Enter your IELTS band score",
          rateValues: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
        },
        {
          type: "text",
          name: "PTE",
          visibleIf:
            '{tests} contains "PTE Academic (Pearsons Test of English Academic)"',
          title: "Enter your PTE Score",
          description: "overall score range is 10-90",
          inputType: "number",
          placeHolder: "10-90"
        },
        {
          type: "radiogroup",
          name: "Cambridge_test",
          visibleIf:
            '{tests} contains "C1 Advanced or C2 Proficiency (Cambridge English: Advanced or Proficiency)"',
          title: "Which Cambridge English Test did you take?",
          choices: [
            "A2 Key",
            "B1 Preliminary",
            "B2 First",
            {
              value: "item1",
              text: "C1 Advanced (CAE)"
            },
            {
              value: "item2",
              text: "C2 Proficiency (CPE)"
            },
            {
              value: "item3",
              text: "B1 Business Preliminary (BEC)"
            },
            {
              value: "item4",
              text: "B2 Business Vantage (BEC Vantage)"
            },
            {
              value: "item5",
              text: "C1 Business Higher (BEC Higher)"
            }
          ]
        },
        {
          type: "text",
          name: "Cambridge_score",
          visibleIf:
            '{tests} contains "C1 Advanced or C2 Proficiency (Cambridge English: Advanced or Proficiency)"',
          title: "What was your score on the Cambridge English test you took?",
          inputType: "number",
          placeHolder: "80-230"
        },
        {
          type: "text",
          name: "SAT_date",
          visibleIf: '{tests} contains "SAT"',
          title: "What year did you take the SAT?",
          description: "you can enter any number for the month and day",
          inputType: "date",
          placeHolder: "YYYY"
        },
        {
          type: "multipletext",
          name: "SAT_score",
          visibleIf: '{tests} contains "SAT"',
          title: "What was your score on each section?",
          items: [
            {
              name: "Evidence-Based Reading and Writing"
            },
            {
              name: "Math"
            },
            {
              name: "Essay (optional)"
            },
            {
              name: "Total Score"
            }
          ]
        },
        {
          type: "multipletext",
          name: "ACT_scores",
          visibleIf: '{tests} contains "ACT"',
          title: "What were your Scores for each section of the ACT",
          items: [
            {
              name: "English"
            },
            {
              name: "Math"
            },
            {
              name: "Reading"
            },
            {
              name: "Science"
            },
            {
              name: "Composite Act Score"
            }
          ]
        }
      ]
    },
    {
      name: "Skills",
      elements: [
        {
          type: "dropdown",
          name: "native_language",
          title: "What is your Native Language (mother tongue)?",
          hasOther: true,
          choices: [
            "Afrikaans",
            "Albanian",
            "Amharic",
            "Arabic (Egyptian Spoken)",
            "Arabic (Levantine)",
            "Arabic (Modern Standard)",
            "Arabic (Moroccan Spoken)",
            "Arabic (Overview)",
            "Aramaic",
            "Armenian",
            "Assamese",
            "Aymara",
            "Azerbaijani",
            "Balochi",
            "Bamanankan",
            "Bashkort (Bashkir)",
            "Basque",
            "Belarusan",
            "Bengali",
            "Bhojpuri",
            "Bislama",
            "Bosnian",
            "Brahui",
            "Bulgarian",
            "Burmese",
            "Cantonese",
            "Catalan",
            "Cebuano",
            "Chechen",
            "Cherokee",
            "Croatian",
            "Czech",
            "Dakota",
            "Danish",
            "Dari",
            "Dholuo",
            "DutchEnglish",
            "Esperanto",
            "Estonian",
            "Éwé",
            "Finnish",
            "French",
            "Georgian",
            "German",
            "Gikuyu",
            "Greek",
            "Guarani",
            "Gujarati",
            "Haitian Creole",
            "Hausa",
            "Hawaiian",
            "Hawaiian Creole",
            "Hebrew",
            "Hiligaynon",
            "Hindi",
            "Hungarian",
            "Icelandic",
            "Igbo",
            "Ilocano",
            "Indonesian (Bahasa Indonesia)",
            "Inuit/Inupiaq",
            "Irish Gaelic",
            "Italian",
            "Japanese",
            "Jarai",
            "Javanese",
            "K’iche’",
            "Kabyle",
            "Kannada",
            "Kashmiri",
            "Kazakh",
            "Khmer",
            "KhoekhoeKorean",
            "Kurdish",
            "Kyrgyz",
            "Lao",
            "Latin",
            "Latvian",
            "Lingala",
            "Lithuanian",
            "Macedonian",
            "Maithili",
            "Malagasy",
            "Malay (Bahasa Melayu)",
            "Malayalam",
            "Mandarin (Chinese)",
            "Marathi",
            "Mende",
            "Mongolian",
            "Nahuatl",
            "Navajo",
            "Nepali",
            "Norwegian",
            "Ojibwa",
            "Oriya",
            "Oromo",
            "Pashto",
            "Persian",
            "Polish",
            "Portuguese",
            "Punjabi",
            "Quechua",
            "Romani",
            "Romanian",
            "Russian",
            "Rwanda",
            "Samoan",
            "Sanskrit",
            "SerbianShona",
            "Sindhi",
            "Sinhala",
            "Slovak",
            "Slovene",
            "Somali",
            "Spanish",
            "Swahili",
            "Swedish",
            "Tachelhit",
            "Tagalog",
            "Tajiki",
            "Tamil",
            "Tatar",
            "Telugu",
            "Thai",
            "Tibetic languages",
            "Tigrigna",
            "Tok Pisin",
            "Turkish",
            "Turkmen",
            "Ukrainian",
            "Urdu",
            "Uyghur",
            "Uzbek",
            "Vietnamese",
            "Warlpiri",
            "Welsh",
            "Wolof",
            "Xhosa",
            "Yakut",
            "Yiddish",
            "Yoruba",
            "Yucatec",
            "Zapotec",
            "Zulu"
          ]
        },
        {
          type: "matrixdynamic",
          name: "other_languages",
          title: "What other Languages do you speak?",
          columns: [
            {
              name: "Language",
              cellType: "dropdown",
              hasOther: true
            },
            {
              name: "Level",
              cellType: "checkbox",
              choices: ["Beginner", "Intermediate", "Advanced"]
            }
          ],
          choices: [
            "Afrikaans",
            "Albanian",
            "Amharic",
            "Arabic (Egyptian Spoken)",
            "Arabic (Levantine)",
            "Arabic (Modern Standard)",
            "Arabic (Moroccan Spoken)",
            "Arabic (Overview)",
            "Aramaic",
            "Armenian",
            "Assamese",
            "Aymara",
            "Azerbaijani",
            "Balochi",
            "Bamanankan",
            "Bashkort (Bashkir)",
            "Basque",
            "Belarusan",
            "Bengali",
            "Bhojpuri",
            "Bislama",
            "Bosnian",
            "Brahui",
            "Bulgarian",
            "Burmese",
            "Cantonese",
            "Catalan",
            "Cebuano",
            "Chechen",
            "Cherokee",
            "Croatian",
            "Czech",
            "Dakota",
            "Danish",
            "Dari",
            "Dholuo",
            "DutchEnglish",
            "Esperanto",
            "Estonian",
            "Éwé",
            "Finnish",
            "French",
            "Georgian",
            "German",
            "Gikuyu",
            "Greek",
            "Guarani",
            "Gujarati",
            "Haitian Creole",
            "Hausa",
            "Hawaiian",
            "Hawaiian Creole",
            "Hebrew",
            "Hiligaynon",
            "Hindi",
            "Hungarian",
            "Icelandic",
            "Igbo",
            "Ilocano",
            "Indonesian (Bahasa Indonesia)",
            "Inuit/Inupiaq",
            "Irish Gaelic",
            "Italian",
            "Japanese",
            "Jarai",
            "Javanese",
            "K’iche’",
            "Kabyle",
            "Kannada",
            "Kashmiri",
            "Kazakh",
            "Khmer",
            "KhoekhoeKorean",
            "Kurdish",
            "Kyrgyz",
            "Lao",
            "Latin",
            "Latvian",
            "Lingala",
            "Lithuanian",
            "Macedonian",
            "Maithili",
            "Malagasy",
            "Malay (Bahasa Melayu)",
            "Malayalam",
            "Mandarin (Chinese)",
            "Marathi",
            "Mende",
            "Mongolian",
            "Nahuatl",
            "Navajo",
            "Nepali",
            "Norwegian",
            "Ojibwa",
            "Oriya",
            "Oromo",
            "Pashto",
            "Persian",
            "Polish",
            "Portuguese",
            "Punjabi",
            "Quechua",
            "Romani",
            "Romanian",
            "Russian",
            "Rwanda",
            "Samoan",
            "Sanskrit",
            "SerbianShona",
            "Sindhi",
            "Sinhala",
            "Slovak",
            "Slovene",
            "Somali",
            "Spanish",
            "Swahili",
            "Swedish",
            "Tachelhit",
            "Tagalog",
            "Tajiki",
            "Tamil",
            "Tatar",
            "Telugu",
            "Thai",
            "Tibetic languages",
            "Tigrigna",
            "Tok Pisin",
            "Turkish",
            "Turkmen",
            "Ukrainian",
            "Urdu",
            "Uyghur",
            "Uzbek",
            "Vietnamese",
            "Warlpiri",
            "Welsh",
            "Wolof",
            "Xhosa",
            "Yakut",
            "Yiddish",
            "Yoruba",
            "Yucatec",
            "Zapotec",
            "Zulu"
          ]
        },
        {
          type: "checkbox",
          name: "skills1",
          title: "What other skills do you have?",
          description: "check all that apply",
          hasOther: true,
          choices: [
            "coding/programming",
            {
              value: "graphic design",
              text: "design"
            },
            "photography",
            "writing",
            "social media management",
            "videography/video editing",
            "audio recording/audio editing"
          ]
        },
        {
          type: "checkbox",
          name: "coding_languages",
          visibleIf: '{skills1} contains "coding/programming"',
          title: "What coding languages are you familiar with?",
          description: "check all that apply",
          hasOther: true,
          choices: ["Python", "Javascript", "SQL", "Shell/Bash", "Markdown"]
        },
        {
          type: "checkbox",
          name: "technologies",
          visibleIf: '{skills1} contains "coding/programming"',
          title: "What technologies have you worked with?",
          description: "Check all that apply",
          hasOther: true,
          choices: [
            "NodeJS",
            "Express",
            "Postgres",
            "React",
            "Redux",
            "TensorFlow",
            "Babel",
            "Webpack",
            "Kubernetes",
            "Docker"
          ]
        },
        {
          type: "text",
          name: "github",
          visibleIf: '{skills1} contains "coding/programming"',
          title: "What is your Github handle?",
          description: "If you don't have one, leave this blank"
        },
        {
          type: "checkbox",
          name: "design",
          visibleIf: '{skills1} contains "graphic design"',
          title: "What are your areas of design expertize?",
          description: "Check all that apply",
          hasOther: true,
          choices: [
            "publishing (books, magazines, flyers, business cards etc...)",
            "user experience (websites, apps)",
            "physical 3-D objects (furniture, small objects)",
            "digital designs (ads, social media posts)",
            "logo, branding designs"
          ]
        },
        {
          type: "checkbox",
          name: "social media",
          visibleIf: '{skills1} contains "social media management"',
          title: "What social media platforms have you managed?",
          description: "Check all that apply",
          hasOther: true,
          choices: [
            "LinkedIN",
            "Twitter",
            "Instagram",
            "Facebook",
            "Pinterest",
            "Tumblr.",
            "YouTube",
            "Vimeo",
            "Google+ (Google my business)"
          ]
        },
        {
          type: "checkbox",
          name: "software",
          title: "What software do you use regularly?",
          description: "Check all that apply",
          hasOther: true,
          choices: [
            "Microsoft Word",
            "Microsoft Excell",
            "Microsoft PowerPoint",
            "Microsoft Access",
            "Microsoft Publisher",
            "Google Docs",
            "Google Sheets",
            "Google Slides",
            "Adobe Photoshop",
            "Adobe Lightroom",
            "Adobe Illustrator",
            "Adobe Premiere Pro",
            "Adobe After Effects",
            "Adobe Audition",
            "Adobe InDesign",
            "Adobe Dreamweaver",
            "Adobe Spark",
            "Adobe XD",
            "iMovie",
            "Audacity",
            "Quickbooks",
            "None"
          ]
        }
      ]
    },
    {
      name: "Work History",
      elements: [
        {
          type: "radiogroup",
          name: "employed",
          title: "Are you currently employed?",
          description: "do not include WorkAround ",
          choices: ["Full-time", "Part-time", "Not currently employed"]
        },
        {
          type: "checkbox",
          name: "why not work",
          visibleIf: '{employed} = "Not currently employed"',
          title: "What are the reasons you are not employed?",
          description: "check all that apply",
          hasOther: true,
          choices: [
            "No work permit/government restrictions",
            "No government ID",
            "Available jobs are not safe",
            "Available jobs don't match my skills",
            "I don't have any previous work experience",
            "I don't speak the language",
            "I don't know where to find a job",
            "I must stay home to take care of children, elderly relatives",
            "I'm going to school instead"
          ]
        },
        {
          type: "matrixdynamic",
          name: "employment history",
          title: "Add your previous jobs",
          columns: [
            {
              name: "Job Title",
              cellType: "text"
            },
            {
              name: "Company Name",
              cellType: "text"
            },
            {
              name: "Industry",
              cellType: "dropdown"
            }
          ],
          choices: [
            "Administrative and Support Services ",
            "Agriculture, Forestry, Fishing and Hunting ",
            "Air Transportation ",
            "Amusement, Gambling, and Recreation Industries ",
            "Animal Production (raising livestock)",
            "Arts, Entertainment, and Recreation ",
            "Banks and other Monetary Authorities",
            "Broadcasting ",
            "Building Material and Garden Equipment and Supplies Dealers ",
            "Chemical Manufacturing ",
            "Clothing and Clothing Accessories Stores ",
            "Clothing Manufacturing ",
            "Computer and Electronic Product Manufacturing ",
            "Construction ",
            "Couriers and Messengers ",
            "Data Processing, Hosting, and Related Services ",
            "Educational Services ",
            "Electrical Equipment, Appliance, and Component Manufacturing ",
            "Electronics and Appliance Stores ",
            "Farming",
            "Financial Activities",
            "Food Manufacturing / Processed foods",
            "Food Services/Restaurants",
            "Forestry and Logging ",
            "Funds, Trusts, and Other Financial Vehicles ",
            "Furniture and Home Furnishings Stores ",
            "Gasoline Stations ",
            "General Merchandise Stores ",
            "Health Care Services (in-home or outpatient care)",
            "Heavy and Civil Engineering Construction ",
            "Hospitals ",
            "Hotels & Hospitality",
            "Insurance ",
            "Internet Publishing and Broadcasting ",
            "Management of Companies and Enterprises ",
            "Manufacturing ",
            "Merchant Wholesalers",
            "Mining, Quarrying, and Oil and Gas Extraction ",
            "Motion Picture and Sound Recording Industries ",
            "Motor Vehicle and Parts Dealers ",
            "Museums, Historical Sites, and Similar Institutions ",
            "NGOs, INGOs, and nonprofit social work",
            "Paper Manufacturing ",
            "Performing Arts, Spectator Sports, and Related Industries ",
            "Personal and Laundry Services ",
            "Petroleum and Coal Products Manufacturing ",
            "Pharmacies",
            "Pipeline Transportation ",
            "Plastics and Rubber Products Manufacturing ",
            "Postal Service ",
            "Printing and Related Support Activities ",
            "Private Households / Family caretakers",
            "Professional and Business Services",
            "Publishing Industries ",
            "Real Estate ",
            "Religious, Grantmaking, Civic, Professional, and Similar Organizations ",
            "Repair and Maintenance ",
            "Scientific, and Technical Services ",
            "Securities, Commodity Contracts, and Other Financial Investments and Related Activities ",
            "Service-Providing Industries",
            "Social Assistance ",
            "Sporting Goods, Hobby, Book, and Music Stores ",
            "Telecommunications ",
            "Textile Mills ",
            "Textile Product Mills ",
            "Transportation ",
            "Utilities (electricity, gas, water etc…)",
            "Warehousing and Storage ",
            "Waste Management",
            "Waste Management and Remediation Services ",
            "Wholesale Trade "
          ]
        },
        {
          type: "file",
          name: "Upload your CV or Resume",
          description: "(optional)",
          maxSize: 0
        }
      ]
    },
    {
      name: "Access",
      elements: [
        {
          type: "checkbox",
          name: "device",
          title: "Which devices do you have?",
          description: "Check all that apply",
          choices: [
            "laptop computer",
            "desktop computer",
            "smartphone",
            "tablet"
          ]
        },
        {
          type: "radiogroup",
          name: "operating system computers",
          visibleIf: '{device} contains "laptop computer"',
          title: "What Operating System do you use?",
          choices: ["Windows", "Mac", "Linux"]
        },
        {
          type: "radiogroup",
          name: "phone_type",
          visibleIf: '{device} contains "smartphone"',
          title: "What operating system is on your phone?",
          choices: ["Android", "iOS (iPhone)"]
        },
        {
          type: "checkbox",
          name: "Where",
          title: "Where do you plan on doing jobs for WorkAround?",
          hasOther: true,
          choices: [
            "home",
            "internet cafe",
            "coffee shop",
            "library",
            "computer lab or work space"
          ]
        },
        {
          type: "radiogroup",
          name: "internet cost1",
          title: "How much do you pay for internet each month?",
          description: "All values are in US dollar",
          choices: [
            "$0",
            "up to $5/month",
            "$6 -$10/month",
            "$11-$20/month",
            "$21-$50/month",
            "$51 or more"
          ]
        },
        {
          type: "radiogroup",
          name: "time",
          title: "How much time do you want to Work on WorkAround each week?",
          choices: [
            "I'll work here and there when I have a few free minutes (0-1 hours/week)",
            "part-time (2-20 hours/week)",
            "full-time (21-40 hours/week)"
          ]
        },
        {
          type: "checkbox",
          name: "notifications",
          title: "How do you prefer to get notifications about new jobs?",
          hasOther: true,
          choices: ["email", "WhatsApp", "Facebook", "on the platform"]
        }
      ]
    },
    {
      name: "Payment",
      elements: [
        {
          type: "radiogroup",
          name: "Bank Account",
          title: "Do you have a bank account in your own name?",
          description:
            "You can still work with WorkAround if you don't have a bank account",
          choices: ["Yes", "No"]
        },
        {
          type: "checkbox",
          name: "other_payment",
          title: "Do you have an account on any of these platforms?",
          description: "Check all that apply",
          hasOther: true,
          choices: [
            "PayPal",
            "Venmo",
            "Transferwise",
            "Payoneer",
            "Veem",
            "AirTM",
            "Skrill"
          ]
        },
        {
          type: "text",
          name: "PayPal",
          visibleIf: '{other_payment} contains "PayPal"',
          title: "What is your PayPal email address?",
          description: "PayPal account must be in your own name",
          validators: [
            {
              type: "email"
            }
          ],
          inputType: "email"
        }
      ]
    }
  ]
}
